apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: infra-system
spec:
  project: default
  source:
    repoURL: https://github.com/jorisvilardell/my-talos-cluster
    targetRevision: main
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
