apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: ouerdia-medium-uat
  namespace: infra-system
spec:
  # Namespace où se trouvent les Applications ArgoCD à gérer
  namespace: infra-system

  # Sélection de l'application ArgoCD à gérer
  applicationRefs:
    - namePattern: "ouerdia-medium-uat"

      # Configuration des images à surveiller et mettre à jour
      images:
        # Image de l'API Backend
        - alias: api
          imageName: ghcr.io/jorisvilardell/ouerdia-medium-api:dev

          # Paramètres de mise à jour pour l'API
          commonUpdateSettings:
            updateStrategy: digest
            allowTags: "dev"

        # Image du Frontend Webapp
        - alias: webapp
          imageName: ghcr.io/jorisvilardell/ouerdia-medium-webapp:dev

          # Paramètres de mise à jour pour le Webapp
          commonUpdateSettings:
            updateStrategy: digest
            allowTags: "dev"

      # Configuration write-back pour cette application
      # Mode argocd : met à jour directement les paramètres de l'Application ArgoCD
      # via kustomize.images, sans gérer les Helm values
      writeBackConfig:
        method: argocd

  # Configuration globale de write-back (fallback)
  writeBackConfig:
    method: argocd
